/**
 * @modified 2009.04.14
 * @since 2003.11.19|1999.02.19 (v00.02.00)
 * @author HoKoNoUmo
 */
package pk_Util;

import java.util.ListResourceBundle;

public class BundleLabels_en_US
	extends ListResourceBundle {

	public Object[][] getContents() {
		return contents;
	}

	static final Object[][] contents = {
		/* COMMON-USED-LABELS: */

		/* ALL CAPITALS: */
		{"CANCEL",								"CANCEL"},
		{"DEFINITION",						"DEFINITION"},
		{"DEFINITION_ATTRIBUTE",	"ATTRIBUTE-DEFINITION"},
		{"DEFINITION_ATTRIBUTE_START", "START-ATTRIBUTE-DEFINITION"},
		{"DEFINITION_ATTRIBUTE_END", 	"END-ATTRIBUTE-DEFINITION"},
		{"DEFINITION_PART",					"PART-DEFINITION"},
		{"DEFINITION_PART_START",		"START-PART-DEFINITION"},
		{"DEFINITION_PART_END",			"END-PART-DEFINITION"},
		{"DEFINITION_WHOLE",					"WHOLE-DEFINITION"},
		{"DEFINITION_WHOLE_START",		"START-WHOLE-DEFINITION"},
		{"DEFINITION_WHOLE_END", 		"END-WHOLE-DEFINITION"},
		{"DEFINITION_SPECIFIC",			"SPECIFIC-DEFINITION"},
		{"DEFINITION_SPECIFIC_START",	"START-SPECIFIC-DEFINITION"},
		{"DEFINITION_SPECIFIC_END",		"END-SPECIFIC-DEFINITION"},
		{"DEFINITION_GENERIC",				"GENERIC-DEFINITION"},
		{"DEFINITION_GENERIC_START",	"START-GENERIC-DEFINITION"},
		{"DEFINITION_GENERIC_END",		"END-GENERIC-DEFINITION"},
		{"DEFINITION_ENVIRONMENT",		"ENVIRONMENT-DEFINITION"},
		{"DEFINITION_ENVIRONMENT_START",	"START-ENVIRONMENT-DEFINITION"},
		{"DEFINITION_ENVIRONMENT_END",	"END-ENVIRONMENT-DEFINITION"},
		{"DEFINITION_SENSORY",				"SENSORY-DEFINITION"},
		{"REFINO",							"RELATION"},
		{"REFINO_ARGUMENT",		"ARGUMENT-RELATION"},
		{"REFINO_ATTRIBUTE",		"ATTRIBUTE-RELATION"},
		{"REFINO_DEFINITION",	"DEFINITION-RELATION"},
		{"REFINO_ENTITY",			"ENTITY-RELATION"},
		{"REFINO_ENVIRONMENT",	"ENVIRONMENT-RELATION"},
		{"REFINO_GENERIC",			"GENERIC-RELATION"},
		{"REFINO_NAME",				"NAME-RELATION"},
		{"REFINO_NONaTTRIBUTE","NON-ATTRIBUTE-RELATION"},
		{"REFINO_PART",				"PART-RELATION"},
		{"REFINO_PARTcOMPLEMENT","PARTIAL-COMPLEMENT--RELATION"},
		{"REFINO_SPECIFIC",		"SPECIFIC-RELATION"},
		{"REFINO_SPECIFICcOMPLEMENT","SPECIFIC-COMPLEMENT--RELATION"},
		{"REFINO_WHOLE",				"WHOLE-RELATION"},
		{"ENVIRONMENT",				"ENVIRONMENT"},
		{"ENVIRONMENTS",				"ENVIRONMENTS"},
		{"GENERIC",						"GENERIC"},
		{"GENERICS",						"GENERICS"},
		{"HELP",								"HELP"},
		{"REFINO_NAME",				"NAME-RELATION"},
		{"FO_ETO_KONCOS_NAMO",	"NAME-OF-LG-CONCEPT"},
		{"FO_ETO_TO_KONCOS_NAMO",	"NAME-OF-TX-CONCEPT"},
		{"TERMS",							"TERMS"},
		{"NAME",								"NAME"},
		{"NEW",								"NEW"},
		{"NO",									"NO"},
		{"OK",									"OK"},
		{"OLD",								"OLD"},
		{"PART",								"PART"},
		{"PARTcOMPLEMENT",			"PARTIAL-COMPLEMENT"},
		{"PARTS",							"PARTS"},
		{"SENSORIALbCONCEPT",	"SENSORIAL--B-CONCEPT"},
		{"SPECIFIC",						"SPECIFIC"},
		{"SPECIFICS",					"SPECIFICS"},
		{"SPECIFICcOMPLEMENT",	"SPECIFIC-COMPLEMENT"},
		{"WHOLE",							"WHOLE"},
		{"WHOLES",							"WHOLES"},
		{"YES",								"YES"},
		{"XMLcONCEPT",					"X-CONCEPT"},

		/* First Capital: */
		{"All",								"All"},
		{"Author",							"Author"},
		{"BWorldview",					"Brainual-worldview"},
		{"Cancel",							"Cancel"},
		{"ChooseLangToUpdate",	"Chose Language to Update"},
		{"ChooseOne",					"Choose One"},
		{"Concept_Tx",					"Textual-concept"},
		{"Conjunction_Tx",			"TxConjunction"},
		{"Created",						"Created"},
		{"Delete",							"Delete"},
		{"Deleted",						"Deleted"},
		{"Description",				"Description"},
		{"Down",								"Down"},
		{"English",						"English"},
		{"English2",						"English"},
		{"EngMainName",				"English-MainName"},
		{"Environment_Relation", "Environment-Relation"},
		{"Esperanto",					"Esperanto"},
		{"FileXCpt",						"File-XCpt"},
		{"Find",								"Find"},
		{"FindRule",						"Find-Rule"},
		{"FormalName",					"Formal-Name"},
		{"FormalNumber",				"Formal-Number"},
		{"FormalID",						"Formal-ID"},
		{"FormalTerm",					"Formal-Term"},
		{"FormalView",					"Formal-View"},
		{"FullName",						"Full-Name"},
		{"Greek",							"Greek"},
		{"Greek2",							"Greek"},
		{"Help",								"Help"},
		{"Insert",							"Insert"},
		{"InternalXCpt",				"Internal-XCpt"},
		{"Komo",								"Komo"},
		{"Language",						"Language"},
		{"Modify",							"Modify"},
		{"MostUsed",						"Most-used"},
		{"Name",								"Name"},
		{"NameConceptLg",			"Name-of-LgConcept"},
		{"Name_NounAdjective",	"Name-of-Adjective"},
		{"Name_NounAdverb",		"Name-of-Adverb"},
		{"Name_Conjunction",		"Name-of-Conjunction"},
		{"NameTxConjunction",	"Name-of-TxConjunction"},
		{"Name_Short",					"Name_Short"},
		{"NameShortTx",				"Short-TxName"},
		{"Name_NounCase",			"Name-of-CaseNoun"},
		{"NameNounTx",					"Name-of-TxNoun"},
		{"Name_Symbol",				"SymbolName"},
		{"Name_NounSpecialAdjective",	"Name-of-SpecialAdjective"},
		{"NamoSpecialoTxNounAdjective",	"Name-of-SpecialTxAdjective"},
		{"Name_NounSpecialAdverb",	"Name-of-SpecialAdverb"},
		{"NamoSpecialoTxNounAdverb",	"Name-of-SpecialTxAdverb"},
		{"Name_NounSpecialCase",		"Name-of-SpecialCaseNoun"},
		{"NamoSpecialoTxNoun",			"Name-of-SpecialTxNoun"},
		{"Name_Verb",							"Name-of-Verb"},
		{"Name_sTypeOfLgConcept","Type-of-NameConceptLg"},
		{"NounAdjectiveTx",			"TxAdjective"},
		{"NounAdverbTx",					"TxAdverb"},
		{"Rel",									"Rel"},
		{"Relation",							"Relation"},
		{"Replace",							"Replace"},
		{"Rule",									"Rule"},
		{"SeeTextDefinition",		"See-Text-Definition"},
		{"SeeXmlDefinition",			"See-XML-Definition"},
		{"SpecificDivisionOn",		"Specific-division-on: "},
		{"SrSubWorldview",				"SrSubWorldview"},
		{"Statistics",						"Statistics"},
		{"Term",									"Term"},
		{"Term_TxConcept",				"Term-of-TxConcept"},
		{"TermTxNounAdjective",	"Term-of-AdjectiveTxNoun"},
		{"TermTxNounAdverb",			"Term-of-AdverbTxNoun"},
		{"TermTxNounCase",				"Term-of-CaseTxNoun"},
		{"TermTxVerb",						"Term-of-TxVerb"},
		{"TermsOfConcept_Tx",		"Terms-Of-TxConcept"},
		{"TxNoun",								"TxNoun"},
		{"TxNounSpecial",				"Special-TxNoun"},
		{"TypeOfCreationDefinition","Type-of-CreationDefinition"},
		{"TypeOfName",						"Type-of-Name"},
		{"UniqueName",						"Unique-Name"},
		{"Up",										"Up"},
		{"Update",								"Update"},
		{"Verb_Tx",							"TxVerb"},
		{"XSubWorldview",				"XSubWorldview"},

		/* all smalls: */
		{"all",									"all"},
		{"analytic-definition",	"analytic-definition"},
		{"attribute",						"attribute"},
		{"author",								"author"},
		{"creation-definition",	"creation-definition"},
		{"deleted",							"deleted"},
		{"english",							"english"},
		{"esperanto",						"esperanto"},
		{"foEkoKoncosNamo",			"name"},
		{"generic",							"generic"},
		{"greek",								"greeek"},
		{"komo",									"komo"},
		{"part",									"part"},
		{"relator",							"relator"},
		{"sensory",							"sensory"},
		{"specific",							"specific"},
		{"txConjunctions",				"tx-conjunctions"},
		{"tx_nouns",							"tx-nouns"},
		{"tx_nounAdjectives",		"tx-adjectives"},
		{"tx_adverbs",						"tx-adverbs"},
		{"txVerbs",							"tx-verbs"},
		{"whole",								"whole"},
		{"xSubWorldView",				"x-sub-worldview"},
		{"xWorldView",						"x-worldview"},

		/* Messages: */
		{"frasisSynMgt",	"(You can manage its sysnonyms, after xcpt-creation)"},
		{"MsgAddNewAtt", "Add a NEW xConcept, as ATTRIBUTE to:   "},
		{"MsgAddNewEnv", "Add a NEW xConcept, as ENVIRONMENT to:   "},
		{"MsgAddNewGeneric", "Add a NEW xConcept, as GENERIC to:   "},
		{"MsgAddNewPart", "Add a NEW xConcept, as PART to:   "},
		{"MsgAddNewSpecific", "Add a NEW xConcept, as SPECIFIC to:   "},
		{"MsgAddNewWhole", "Add a NEW xConcept, as WHOLE to:   "},
		{"MsgAddDefRel", "<html><center>Add definition's relations as: ( [Rel] {arg1} {([]{})} {arg3} ) <br/>Use any UNIQUE-NAME for the sr-cpts rel/arg <br/>Use the special-names: PartRefino, WholeRefino, SpecificRefino, GenericRefino, EnvironmentRefino, AttributeRefino, EntityRefino."},
		{"MsgChooseSrWV",	"Choose Sensorial-Worldview"},
		{"MsgDefGive",			"You MUST give a DEFINITION"},
		{"MsgMainName", 		"You MUST give a Main-Name in english"},
		{"MsgPreferInternals", "(Prefer Internals when the definition is enough to create it)"},



		/* ALPHABETICALLY PER OBJECT: */

		/* ABOUT DIALOG: */
		{"About1",			"java XConcept-Program"},
		{"About2",			"version: 00.02.01"},
		{"About3",			"created: 1997.05.12"},
		{"About4",			"author: Nikos Kasselouris"},
		{"About5",			"email: nikkas@otenet.gr"},
		{"About6",			"url: http://users.otenet.gr/~nikkas/"},

		/* FrameAddNewSpecific.java: */
		{"fansTitle",		"Add a NEW xcpt, as SPECIFIC to ("},

		/* FrameAddUnrelated.java: */
		{"fauTitle",			"Add a NEW UNRELATED xcpt"},

		/* RetrieveFrame_FindTxConceptTerms: */
		{"ffnTitle",				"Find TERMS Of TX-CONCEPT"},
		{"ffnMessage",			"Write the NAME-OF-TX-CONCEPT, choose a RULE to create its TERMS *OR* let the computer to find the appropriate"},
		{"ffnRuleForce",		"Force-Rule:"},
		{"ffnRule",				"Choose-Rule:"},
		{"ffnTxConceptTerms","Terms-of-TxConcept:"},
		{"ffnFind",				"Find Terms-of-TxConcept"},

		/* RetrieveFrame_KBInfo.java: */
		{"fkbiTitle",			"XKnowledgeBase Statistics"},

		/* FrameRenameCurrentCpt.java: */
		{"frccTitle",			"Rename CURRENT xcpt"},
		{"frccNameEl",			"Greek-Name:"},
		{"frccNameEn",			"English-Name:"},
		{"frccType",				"type:"},

		/* FrameNameManagement.java: */
		{"fnmgtTitle",					"Names of Current-Concept Management"},
		{"fnmgtTmrRule",				"Term-rule:"},
		{"fnmgtCurrent1",			"current"},
		{"fnmgtCurrent2",			"current"},
		{"fnmgtDeletePermanent","Delete Permanent"},
		{"fnmgtTipInsert",			"Insert Name AFTER selected name"},
		{"fnmgtTipModify",			"Modify selected Name"},
		{"fnmgtTipDelete",			"Sets DELETION-DATE in selected Name"},
		{"fnmgtTipDeletePermanent",		"DELETES-PERMANENT the selected Name"},
		{"fnmgtTipOK",					"Update Lango-LgConcept-Names and Close the window"},
		{"fnmgtTipUpdate",			"Update names of CURRENT-LANGUAGE"},
		{"fnmgtMsgSelect",			"You MUST select a name!!!"},
		{"fnmgtMsgModify",			"Modifing rule or lg-concept's--name, old names are orphan!!!"},
		{"fnmgtMsgName",				"The MAIN-NAME of an xcpt is its FIRST-Name-of-CaseNoun"},

		/* Frame_TxTerminalKomo_Mgt.java: */
		{"ftkmTitle",				"Management of Komo-Terms"},
		{"ftkmLCreate",			"Create Komo-Terms"},
		{"ftkmLUses",				"Uses:"},
		{"ftkmLSilFrs",			"First-Syllable:"},
		{"ftkmLSilMid",			"Middle-Syllable:"},
		{"ftkmLChoose",			"Choose:"},
		{"ftkmLSilNum",			"Syll:"},
		{"ftkmLPref",				"Prefix:"},
		{"ftkmLSuf",					"Suffix:"},
		{"ftkmLWrite",				"Write:"},
		{"ftkmCreate",				"Create Word"},
		{"ftkmCreateValidate","Create & Validate Term"},
		{"ftkmTxWord",				" New Term: "},
		//------------------------------------
		{"ftkmLValidate",		"Validate Komo-Term"},
		{"ftkmTxWord2",			"Write Term: "},
		{"ftkmValidate",			"Validate Term"},
		//------------------------------------
		{"ftkmError1",				"Prefix has TOO MANY syllables."},
		{"ftkmError2",				"Suffix has TOO MANY syllables."},
		{"ftkmError3",				"Choose MORE syllables."},


		/* AAj.java: */
		{"chooseLangOfSynToUpdate",		"Choose the LANGUAGE of Terms you want to update"},
		/* MISC: */
		{"integrated",					"integrated"},
		{"nonIntegrated",			"NON-integrated"},
		{"viewer_sTextPaneTip","Double-Click on a term to FIND the corresponding xcpt"},
		{"titleLabel",					"AAj (java XConcept-Program)"},
		/* VIEWER-SEARCH: */
		{"LabelFindBy",				"Find X-CONCEPT by: "},
		{"ButtonFindByRelated","Related"},
		/*	VIEWER-TREE: */
		{"PART:NAME",					"PART: NAME"},
		{"parCmp",							"PARTIAL-COMPLEMENT"},
		{"nih",								"PART: Non-Inherited:"},
		{"inh",								"PART: Inherited from: "},
		{"sib",								"SIBLING--X-CONCEPT"},
		{"specificCmp",				"SPECIFIC-COMPLEMENT"},

	};
}
