/**
 * @modified 2006.01.31
 * @since 2003.11.19|1999.02.19 (v00.02.00)
 * @author HoKoNoUmo
 */
package pk_Util;

import java.util.ListResourceBundle;

public class BundleLabels_el_GR
	extends ListResourceBundle {

	public Object[][] getContents() {
		return contents;
	}

	static final Object[][] contents = {

		/* COMMON-USED-LABELS: */

		/* ALL CAPITALS: */
		{"CANCEL",										"ΑΚΥΡΩΣΕ"},
		{"DEFINITION",								"ΟΡΙΣΜΟΣ"},
		{"DEFINITION_ATTRIBUTE",			"ATTRIBUTE-DEFINITION"},
		{"DEFINITION_ATTRIBUTE_START", "START-ATTRIBUTE-DEFINITION"},
		{"DEFINITION_ATTRIBUTE_END", 	"END-ATTRIBUTE-DEFINITION"},
		{"DEFINITION_PART",					"PART-DEFINITION"},
		{"DEFINITION_PART_START",		"START-PART-DEFINITION"},
		{"DEFINITION_PART_END",			"END-PART-DEFINITION"},
		{"DEFINITION_WHOLE",					"WHOLE-DEFINITION"},
		{"DEFINITION_WHOLE_START",		"START-WHOLE-DEFINITION"},
		{"DEFINITION_WHOLE_END", 		"END-WHOLE-DEFINITION"},
		{"DEFINITION_SPECIFIC",			"SPECIFIC-DEFINITION"},
		{"DEFINITION_SPECIFIC_START",	"START-SPECIFIC-DEFINITION"},
		{"DEFINITION_SPECIFIC_END",		"END-SPECIFIC-DEFINITION"},
		{"DEFINITION_GENERIC",				"GENERIC-DEFINITION"},
		{"DEFINITION_GENERIC_START",	"START-GENERIC-DEFINITION"},
		{"DEFINITION_GENERIC_END",		"END-GENERIC-DEFINITION"},
		{"DEFINITION_ENVIRONMENT",		"ENVIRONMENT-DEFINITION"},
		{"DEFINITION_ENVIRONMENT_START",	"START-ENVIRONMENT-DEFINITION"},
		{"DEFINITION_ENVIRONMENT_END",	"END-ENVIRONMENT-DEFINITION"},
		{"DEFINITION_SENSORY",				"ΟΡΙΣΜΟΣ-ΑΠΟ-ΑΙΣΘΗΣΕΙΣ"},
		{"REFINO",							"ΣΧΕΣΗ-ΜΕ-ΚΑΤΕΥΘΥΝΣΗ"},
		{"REFINO_ARGUMENT",		"ΟΡΙΣΜΑΤΟΣ-ΣΧΕΣΗ"},
		{"REFINO_ATTRIBUTE",		"ΧΑΡΑΚΤΗΡΙΣΤΙΚΟΥ-ΣΧΕΣΗ"},
		{"REFINO_DEFINITION",	"ΟΡΙΣΜΟΥ-ΣΧΕΣΗ"},
		{"REFINO_ΕΝΤΙΤΥ",			"ΟΝΤΟΤΗΤΑΣ-ΣΧΕΣΗ"},
		{"REFINO_ENVIRONMENT",	"ΠΕΡΙΒΑΛΛΟΝΤΟΣ-ΣΧΕΣΗ"},
		{"REFINO_GENERIC",			"ΓΕΝΙΚΗΣ-ΣΧΕΣΗ"},
		{"REFINO_NAME",				"ΟΝΟΜΑΤΟΣ-ΣΧΕΣΗ"},
		{"REFINO_NONaTTRIBUTE","ΜΗ-ΧΑΡΑΚΤΗΡΙΣΤΙΚΟΥ-ΣΧΕΣΗ"},
		{"REFINO_PART",				"ΜΕΡΟΥΣ-ΣΧΕΣΗ"},
		{"REFINO_PARTcOMPLEMENT","ΜΕΡΟΥΣ-ΣΥΜΠΛΗΡΩΜΑΤΙΚΗ--ΣΧΕΣΗ"},
		{"REFINO_SPECIFIC",		"ΕΙΔΙΚΗΣ-ΣΧΕΣΗ"},
		{"REFINO_SPECIFICcOMPLEMENT","ΕΙΔΙΚΗΣ-ΣΥΜΠΛΗΡΩΜΑΤΙΚΗ--ΣΧΕΣΗ"},
		{"REFINO_WHOLE",				"ΟΛΟΥ-ΣΧΕΣΗ"},
		{"ENVIRONMENT",				"ΠΕΡΙΒΑΛΛΟΝ"},
		{"ENVIRONMENTS",				"ΠΕΡΙΒΑΛΛΟΝ"},
		{"GENERIC",						"ΓΕΝΙΚH"},
		{"GENERICS",						"ΓΕΝΙΚΕΣ"},
		{"HELP",								"ΒΟΗΘΕΙΑ"},
		{"FO_ETO_KONCOS_NAMO",	"ΟΝΟΜΑ"},
		{"FO_ETO_TO_KONCOS_NAMO",	"ΟΝΟΜΑ"},
		{"TERMS",							"ΟΡΟΙ"},
		{"NAME",								"ΟΝΟΜΑ"},
		{"NEW",								"ΝΕΟ"},
		{"NO",									"ΟΧΙ"},
		{"OK",									"ΝΑΙ"},
		{"OLD",								"ΠΑΛΙΟ"},
		{"PART",								"ΜΕΡΟΣ"},
		{"PARTcOMPLEMENT",	"ΣΥΜΠΛΗΡΩΜΑΤΙΚΗ-ΜΕΡΟΥΣ"},
		{"PARTS",							"ΜΕΡΗ"},
		{"SENSORIALbCONCEPT",		"ΑΙΣΘΗΤΗ-ENNOIA"},
		{"SPECIFIC",						"ΕΙΔΙΚΗ"},
		{"SPECIFICS",					"ΕΙΔΙΚΕΣ"},
		{"SPECIFICcOMPLEMENT",	"ΣΥΜΠΛΗΡΩΜΑΤΙΚΗ-ΕΙΔΙΚΗΣ"},
		{"WHOLE",							"ΟΛΟ"},
		{"WHOLES",							"ΟΛΑ"},
		{"YES",								"ΝΑΙ"},
		{"XMLcONCEPT",					"XΕΝΝΟΙΑ"},

		/* First Capital: */
		{"All",									"All"},
		{"Author",								"Author"},
		{"BWorldview",						"Κοσμοθεώρηση"},
		{"Cancel",								"Ακύρωσε"},
		{"ChooseLangToUpdate",		"Διάλεξε Γλώσσα για Ενημέρωση"},
		{"ChooseOne",						"Διάλεξε ένα"},
		{"Created",							"Created"},
		{"Concept_Tx",						"Εννοια-γραπτή"},
		{"Conjunction_Tx",				"Σύνδεσμος-γραπτός"},
		{"Delete",								"Διέγραψε"},
		{"Deleted",							"Διαγράφτηκε"},
		{"Description",					"Description"},
		{"Down",									"Κάτω"},
		{"English",							"Αγγλικός"},
		{"English2",							"Αγγλική"},
		{"EngMainName",					"Αγγλικό-Κύριο-Όνομα"},
		{"Environment_Relation", "Σχέση Περιβάλλοντος"},
		{"Esperanto",						"Εσπεράντο"},
		{"FileXCpt",							"File-XCpt"},
		{"Find",									"Βρες"},
		{"FindRule",							"Βρες-Κανόνα"},
		{"FormalID",							"Formal-ID"},
		{"FormalName",						"Τυπικό-Όνομα"},
		{"FormalNumber",					"Τυπικός-Αριθμός"},
		{"FormalTerm",						"Τυπικός-Όρος"},
		{"FormalView",						"Formal-View"},
		{"FullName",							"Full-Name"},
		{"Greek",								"Ελληνικός"},
		{"Greek2",								"Ελληνική"},
		{"Help",									"Βοήθεια"},
		{"Insert",								"Πρόσθεσε"},
		{"InternalXCpt",					"Internal-XCpt"},
		{"Komo",									"Κοινός"},
		{"Language",							"Γλώσσα"},
		{"Modify",								"Αλλαξε"},
		{"MostUsed",							"Most-used"},
		{"Name",									"Ονομα"},
		{"NameConceptLg",				"Ονομα-έννοιας-λόγου"},
		{"Name_Conjunction",			"Ονομα-συνδέσμου"},
		{"Name_NounAdjective",		"Ονομα-επιθέτου"},
		{"Name_NounAdverb",				"Ονομα-επιρρήματος"},
		{"Name_NounCase",					"Ονομα-πτωτικού"},
		{"Name_NounSpecialAdjective",	"Name_NounSpecialAdjective"},
		{"Name_NounSpecialAdverb",	"Name_NounSpecialAdverb"},
		{"Name_NounSpecialCase",		"Name_NounSpecialCase"},
		{"NameNounTx",						"Ονομα-ουσιαστικού-γραπτό"},
		{"Name_Short",						"Ονομα-σύντομο"},
		{"NameShortTx",					"Ονομα-σύντομο-γραπτό"},
		{"Name_Symbol",						"Ονομα-με-σύμβολα"},
		{"NameTxConjunction",		"Ονομα-συνδέσμου-γραπτού"},
		{"TermsOfConcept_Tx",			"Οροι-έννοιας-γραπτής"},
		{"NamoSpecialoTxNounAdjective",	"NamoSpecialoTxNounAdjective"},
		{"NamoSpecialoTxNounAdverb",	"NamoSpecialoTxNounAdverb"},
		{"NamoSpecialoTxNoun",		"NamoSpecialoTxNoun"},
		{"Name_Verb",							"Ονομα-ρήματος"},
		{"Name_sTypeOfLgConcept",	"Type-of-NameConceptLg"},
		{"NounAdjectiveTx",			"Επίθετο"},
		{"NounAdverbTx",					"Επίρημα"},
		{"Rel",									"Σχ"},
		{"Relation",							"Σχέση"},
		{"Replace",							"Αντικατάστησε"},
		{"Rule",									"Κανόνας"},
		{"SeeTextDefinition",		"Δες-Ορισμό-Κειμένου"},
		{"SeeXmlDefinition",			"Δες-XML-Ορισμό"},
		{"SpecificDivisionOn",		"Ειδική-διαίρεση-ως-προς: "},
		{"SrSubWorldview",				"SrSubWorldview"},
		{"Statistics",						"Statistics"},
		{"TxNoun",								"Ουσιαστικό"},
		{"TxNounSpecial",				"Αντωνυμία"},
		{"Term",									"Ορος"},
		{"Term_TxConcept",				"Ορος-γραπτός-έννοιας"},
		{"TermTxNounCase",				"Ορος-γραπτός-πτωτικού"},
		{"TermTxNounAdjective",	"Ορος-γραπτός-επιθέτου"},
		{"TermTxNounAdverb",			"Ορος-γραπτός-επιρρήματος"},
		{"TermTxVerb",						"Ορος-γραπτός-ρήματος"},
		{"TypeOfCreationDefinition","Τύπος-Ορισμού-Δημιουργίας"},
		{"TypeOfName",						"Τύπος-Ονόματος"},
		{"UniqueName",						"Μοναδικό-Όνομα"},
		{"Up",										"Πάνω"},
		{"Update",								"Ενημέρωσε"},
		{"Verb_Tx",							"Ρήμα"},
		{"XSubWorldview",				"XSubWorldview"},

		/* all smalls: */
		{"all",								"όλα"},
		{"analytic-definition","αναλυτικός-ορισμός"},
		{"attribute",					"χαρακτηριστικό"},
		{"author",							"συγγραφέας"},
		{"creation-definition","ορισμός-δημιουργίας"},
		{"english",						"αγγλική"},
		{"esperanto",					"εσπεράντο"},
		{"foEkoKoncosNamo",		"όνομα"},
		{"xSubWorldView",			"υποΚοσμοθεώρηση"},
		{"generic",						"γενικό"},
		{"greek",							"ελληνική"},
		{"komo",								"κοινή"},
		{"part",								"μέρος"},
		{"relator",						"σχεσιακό"},
		{"sensory",						"αισθητή"},
		{"specific",						"ειδικό"},
		{"xWorldView",					"κοσμοθεώρηση"},
		{"txConjunctions",			"σύνδεσμοι"},
		{"tx_nouns",						"ουσιαστικά"},
		{"tx_nounAdjectives",	"επίθετα"},
		{"tx_adverbs",					"επιρρήματα"},
		{"txVerbs",						"ρήματα"},
		{"whole",							"όλο"},

		/* MultiWord: */
		{"frasisSynMgt",	"(You can manage its sysnonyms, after sr-concept-creation)"},
		{"MsgAddNewAtt", "Add a NEW concept, as ATTRIBUTE to:   "},
		{"MsgAddNewEnv", "Add a NEW xConcept, as ENVIRONMENT to:   "},
		{"MsgAddNewGeneric", "Add a NEW xConcept, as GENERIC to:   "},
		{"MsgAddNewPart", "Add a NEW xConcept, as PART to:   "},
		{"MsgAddNewSpecific", "Πρόσθεσε ΚΑΙΝΟΥΡΓΙΑ x-έννοια, σαν ΕΙΔΙΚΗ στην:   "},
		{"MsgAddNewWhole", "Add a NEW xConcept, as WHOLE to:   "},
		{"MsgAddDefRel", "<html>Add definition's relations as: ( [Rel] {arg1} {([]{})} {arg3} ) <br/>Use any UNIQUE-NAME for the sr-cpts rel/arg"},
		{"MsgChooseSrWV",	"Διάλεξε Κοσμοθεώρηση"},
		{"MsgDefGive",			"You MUST give a DEFINITION"},
		{"MsgMainName",		 "You MUST give a Main-Name in english"},
		{"MsgPreferInternals", "(Prefer Internals when the definition is enough to create it)"},

		/* ALPHABETICALLY PER CLASS: */

		/* ABOUT DIALOG: */
		{"About1",			"Διαχείριση Κοσμοθεωρήσεων με Java"},
		{"About2",			"έκδοση: early alpha"},
		{"About3",			"Κατασκευή: 1997-μάιος-12"},
		{"About4",			"Κατασκευαστής: Νίκος Κασσελούρης"},
		{"About5",			"email: nikkas@otenet.gr"},
		{"About6",			"url: http://users.otenet.gr/~nikkas/"},

		/* FrameAddNewSpecific.java: */
		{"fansTitle",			"Add a NEW concept, as SPECIFIC to ("},

		/* FrameAddUnrelated.java: */
		{"fauTitle",			"Add a NEW UNRELATED concept"},
		{"fauSyn",				"(You can manage its sysnonyms, after concept-creation)"},

		/* RetrieveFrame_FindTxConceptTerms: */
		{"ffnTitle",					"Βρες τους ΟΡΟΥΣ ενός ΟΝΟΜΑΤΟΣ"},
		{"ffnMessage",				"Γράψε τον ΝΕΪΜΕΡ μιας Αγγλ/Ελλην έννοιας και διάλεξε ένα ΚΑΝΟΝΑ-ΚΛΙΣΗΣ της *Ή* άσε το κομπιούτερ να διαλέξει τον καταλληλότερο."},
		{"ffnRuleForce",			"Επέβαλε-Κανόνα:"},
		{"ffnRule",					"Διάλεξε-Κανόνα:"},
		{"ffnTxConceptTerms",	"Μορφές:"},
		{"ffnFind",					"Βρες τις Μορφές"},

		/* RetrieveFrame_KBInfo.java: */
		{"fkbiTitle",			"ΑισθητήςΒάσηςΓνώσεων Στατιστικά"},

		/* FrameRenameCurrentCpt.java: */
		{"frccTitle",			"Rename Current-Concept"},
		{"frccNameEl",			"Ελληνικό-Όνομα:"},
		{"frccNameEn",			"Αγγλικό-Όνομα:"},
		{"frccType",				"τύπος:"},

		/*FrameNameManagement.java: */
		{"fnmgtTitle",				"Διαχείριση Ονομάτων Τρέχουσας Έννοιας"},
		{"fnmgtTmrRule",			"κανόνας όρων:"},
		{"fnmgtCurrent1",		"τρέχων"},
		{"fnmgtCurrent2",		"τρέχουσα"},
		{"fnmgtDeletePermanent","Delete Permanent"},
		{"fnmgtTipInsert",		"Insert Name AFTER selected name"},
		{"fnmgtTipModify",		"Modify selected Name"},
		{"fnmgtTipDelete",		"Sets DELETION-DATE in selected Name"},
		{"fnmgtTipDeletePermanent",		"DELETES-PERMANENT the selected Name"},
		{"fnmgtTipOK",				"Update Lango-LgConcept-Names and Close the window"},
		{"fnmgtTipUpdate",		"Update names of CURRENT-LANGUAGE"},
		{"fnmgtMsgSelect",		"ΠΡΕΠΕΙ πρώτα να επιλέξεις κάποιο συνώνυμο!!!"},
		{"fnmgtMsgModify",		"Modifing rule or lg-concept's--name, old names are orphan!!!"},
		{"fnmgtMsgName",			"Το ΚΥΡΙΟ-ΟΝΟΜΑ αισθητής-έννοιας είναι το ΠΡΩΤΟ όνομα του πτωτικού-ουσιαστικού της"},

		/* Frame_TxTerminalKomo_Mgt.java: */
		{"ftkmTitle",				"Διαχείριση ΓραπτώνΌρων της Κόμο"},
		{"ftkmLCreate",			"Create Komo-Words"},
		{"ftkmLUses",				"Uses:"},
		{"ftkmLSilFrs",			"First-Sil:"},
		{"ftkmLSilMid",			"Middle-Sil:"},
		{"ftkmLChoose",			"Choose:"},
		{"ftkmLSilNum",			"Sil:"},
		{"ftkmLPref",				"Prefix:"},
		{"ftkmLSuf",					"Suffix:"},
		{"ftkmLWrite",				"Write:"},
		{"ftkmCreate",				"Create Word"},
		{"ftkmCreateValidate","Create & Validate Word"},
		{"ftkmTxWord",				" New Word: "},
		//------------------------------------
		{"ftkmLValidate",		"Validate a Komo-Word"},
		{"ftkmTxWord2",			"Write a Word: "},
		{"ftkmValidate",			"Validate Word"},
		//------------------------------------
		{"ftkmError1",				"Prefix has TOO MANY syllables."},
		{"ftkmError2",				"Suffix has TOO MANY syllables."},
		{"ftkmError3",				"Choose MORE syllables."},

		/* AAj.java */
		/* MISC */
		{"integrated",					"ολοκληρωμένη"},
		{"nonIntegrated",			"ΜΗ-ολοκληρωμένη"},
		{"viewer_sTextPaneTip",				"Κάντε Διπλό-Κλικ σε μια λέξη για να βρείτε την αντίστοιχη έννοια"},
		{"titleLabel",					"AAj (Java-ΑισθητήςΕννοιας-Πρόγραμμα)"},
		{"LabelFindBy",				"ΨΑΞΕ με βάση:"},
		{"ButtonFindByRelated","σχετικές"},
		/*	VIEWER-TREE */
		{"PART:NAME",					"ΜΕΡΟΣ: ΟΝΟΜΑΤΑ"},
		{"parCmp",							"ΜΕΡΟΥΣ-ΣΥΜΠΛΗΡΩΜΑΤΙΚΗ"},
		{"nih",								"Μη-Κληρονομημένες:"},
		{"inh",								"Κληρονομημένες από: "},
		{"specificCmp",				"ΕΙΔΙΚΗΣ-ΣΥΜΠΛΗΡΩΜΑΤΙΚΗ"},

	};
}
